### ISSUE TITLE
Handle separate Dockerfile per tool

### ISSUE THREAD

**Issue by pauleve** [colomoto/colomoto-docker#1]
We should investigate how to provide both
- a single docker image which contain all the tools and the web notebook
- one docker per tool

Ideally, each tool should come with an independant Dockerfile, and then an automated? process merge them all in a single build.

Possible direction: docker combine

**Comment by aurelien-naldi** [comment]
For the record, with the current structure we could have per-tool Dockerfile extending our base image and adding a single "conda install" command instead of the longer list from our main Dockerfile. I'm not convinced it would be very useful though.
