### ISSUE TITLE
tmpnb instance

### ISSUE THREAD

**Issue by pauleve** [colomoto/colomoto-docker#10]
For peer-review and occasional demo, it would be nice to have a `tmpnb` (https://github.com/jupyter/tmpnb) instance running somewhere.

Exemple for the pint docker image: http://tmpnb.loicpauleve.name

I can change the docker image to be the one of colomoto ; then we could make a transparent proxy on colomoto.org to access it through http://tmpnb.colomoto.org for instance.

**Comment by pauleve** [comment]
http://tmpnb.loicpauleve.name now runs an instance of colomoto/colomoto-docker.
You can add
```
tmpnb CNAME tmpnb.loicpauleve.name.
```
to your DNS zone (or give me the subdomain of your choice so I can configure nginx appropriately).

**Comment by aurelien-naldi** [comment]
Julio registered the colomoto.org domain some years ago, but the connection settings that he shared with me no longer work. I'll ask him if he can add this entry.

**Comment by aurelien-naldi** [comment]
Julio added the alias to your server: tmpnb.colomoto.org works for me now
