### ISSUE TITLE
aeon.py 0.2 breaks validation

### ISSUE THREAD

**Issue by pauleve** [colomoto/colomoto-docker#116]
See #115 
```
------------------
from biodivine_aeon import *
from pathlib import Path
import cellcollective

# Load the network from CellCellective.
sbml = cellcollective.load("https://research.cellcollective.org/#module/36604:1/signaling-pathway-for-butanol-production-in-clostridium-beijerinckii-nrrl-b598/10")

# Open the loaded SBML and parse it as a Boolean network.
model = BooleanNetwork.from_sbml(Path(sbml.localfile).read_text())
print(f"Loaded model with {model.num_vars()} variables.")
------------------

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 from biodivine_aeon import *
      2 from pathlib import Path
      3 import cellcollective

File /opt/conda/lib/python3.9/site-packages/biodivine_aeon/__init__.py:1, in <module>
----> 1 from .biodivine_aeon import *
      3 __doc__ = biodivine_aeon.__doc__
      4 if hasattr(biodivine_aeon, "__all__"):

ImportError: /opt/conda/lib/python3.9/site-packages/biodivine_aeon/biodivine_aeon.abi3.so: undefined symbol: __libc_single_threaded
ImportError: /opt/conda/lib/python3.9/site-packages/biodivine_aeon/biodivine_aeon.abi3.so: undefined symbol: __libc_single_threaded

Error: Process completed with exit code 1.
```

Ping @daemontus  :-)

**Comment by daemontus** [comment]
Interesting... I recall I had some problems with `libc` incompatibility in the past... at first glance, this does not seem to be related though. I am looking into it...

**Comment by pauleve** [comment]
maybe that glibc 2.32 or later is required ; I see patches introducing this symbol later than 2.31.
I'll try switching to debian testing.

**Comment by daemontus** [comment]
Hmm... the only related thing I can think of right now is that we are currently building using `manylinux_2_28`. In theory this should be fine, since this should imply `glibc>=2.28`, but maybe we can switch to `2_24`? AFAIK Rust should be also fine with anything `glibc>=1.17`, so I don't see why that should increase the dependency.

**Comment by pauleve** [comment]
In the fixed environment, the notebook "Partially specified networks in AEON.ipynb" fails with
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[28], line 6
      3 reachable_reloaded = graph.empty_colored_vertices().copy_with_raw_string(reachable_string) 
      5 # r1 <=> r2 must be a tautology if the sets are equivalent:
----> 6 reachable_reloaded.to_bdd().iff(reachable.to_bdd()).is_true()

AttributeError: 'builtins.Bdd' object has no attribute 'iff'
AttributeError: 'builtins.Bdd' object has no attribute 'iff'
```

**Comment by pauleve** [comment]
Apparently, `iff`, and related methods (xor, imp, and_not) should be prefixed with `l_`, correct?

**Comment by daemontus** [comment]
Yes, I believe that should be the only breaking change in the notebooks that we have here in Colomoto. We decided to prefix these methods with `l_` because `and`/`or` are not valid function names and it was weird to have `iff`/`imp`/`xor` as normal methods while at the same time needing special handling for `and`/`or`.
