### ISSUE TITLE
New tool: BoolSim

### ISSUE THREAD

**Issue by pauleve** [colomoto/colomoto-docker#14]
* [X] conda package for binaries
* [x] Python API
* [x] Example Notebook

**Comment by aurelien-naldi** [comment]
I added a conda package for boolsim, but it still lacks a python wrapper for proper integration.

See https://anaconda.org/colomoto/boolsim

**Comment by pauleve** [comment]
Is there any documentation on boolsim usage?

**Comment by pauleve** [comment]
I started a quick Python interface at https://github.com/pauleve/boolSim-python
Currently, only the attractors computation is implemented, but it is probably sufficient as a start.
Here is a small tutorial https://nbviewer.jupyter.org/github/pauleve/boolSim-python/blob/main/examples/Tutorial.ipynb
(it requires colomoto_jupyter in master version for displaying complex attractors).

I'll make the release and PR by the end of the month so it is shipped in the `2020-08-01` image.

**Comment by aurelien-naldi** [comment]
Thanks! I have also started a quick wrapper here: https://github.com/aurelien-naldi/reversed-model-demo
It lacks proper integration but it can compute reachable states and use espresso to simplify the list of states.

I can add these features to your wrapper, it would also make sense to move the repository to the colomoto organization. Do you have the rights to create new repositories there?

**Comment by pauleve** [comment]
No I have no right to create a repository there - it is a good idea to move it.
Fort the list of states simplification, it may be good to move it to the generic `colomoto.TrapSpacesAttractor` class, so other tools can benefit of it.

**Comment by aurelien-naldi** [comment]
You should now be able to add repositories.

I agree that simplification of states should be a shared feature. It would make sense to detect espresso at import time and add the simplify method there if it is available.
I was about to say I didn't like the name of the generic class for lists of states but the edited name is a better fit ;)

**Comment by pauleve** [comment]
Cool :-) Yes, good idea for the detection of espresso (could be a conda dependency of colomoto_jupyter though).

**Comment by pauleve** [comment]
I implemented the reachable state; I can try to adapt the simplification in `colomoto.types.HypercubeCollection`, but I need to understand the input/output format of espresso :-)

**Comment by pauleve** [comment]
I adapted your espresso call in the `simplify()` method for `HypercubeCollection` object: https://github.com/colomoto/colomoto-jupyter/commit/9666f2673bb084df7fd86cfd74edd3530e1a05db.
I'll implement `boolsim.difference` and `boolsim.intersection` asap and make the release and PR.

**Comment by pauleve** [comment]
Done (https://github.com/colomoto/boolSim-python/commit/7a1ce4dad45bfde898fe0b442cbc456fe4f8321b)
I think we know have everything except the experiment method, so I'll release it by Friday.
Here is a quick adaptation of your notebook: https://gist.github.com/pauleve/3a9f6b433d19f7dc2ac47cfefc7b0210

**Comment by pauleve** [comment]
One possible glitch: for the update mode, in the documentation  they say 
```
-p 1 → synchronous
-p 2 → asynchronous (slow, do not use)
-p 3 → asynchronous (fast)
```
but `boolSim -h` says:
```
  -p, --update-mode=MODE           MODE=1 synchronous.
                                        2 asynchronous.
                                        3 synchronous+asynchronous combined.
```
which is not the same at all... any idea of what is actually implemented?
Currently I use 3 for asynchronous, but I may fall back to 2 if it is not sorted out..

**Comment by aurelien-naldi** [comment]
I our work on reversed models, Julien Dorier told us to use "-p 3", but I don't recall the full discussion.
I did some tests: both give the correct asynchronous successors (and not the synchronous one), so we can keep it as is

**Comment by pauleve** [comment]
Indeed, the basic check
```py
bn = BooleanNetwork({"a": "b", "b": "a"})
boolsim.reachable(bn, {"a": 1, "b": 0})
```
works as expected with (fully) asynchronous only mode. :relieved:
