### ISSUE TITLE
New tool: Boolnet

### ISSUE THREAD

**Issue by pauleve** [colomoto/colomoto-docker#15]

**Comment by aurelien-naldi** [comment]
I added an r-boolnet conda package, but didn't add it yet to the dependencies of the metapackage.

As BoolNet is R only, proper integration will require some further work, we could for example use RPy2.

**Comment by aurelien-naldi** [comment]
I did some quick tests with adding the BoolNet package in the docker image: we can add r-base (it should work with 3.4), r-igraph, and r-irkernel in the base image, then r-boolnet in the complete image. We can easily get it working in a separate R notebook, before working on integration in the python notebook

**Comment by pauleve** [comment]
You can push it in a new branch `next-boolnet` (it will create a docker image with this tag) to ease testing if you want.

**Comment by pauleve** [comment]
Useful resources for binding python and R:
- mixing python and R in jupyter: https://revolution-computing.typepad.com/.a/6a010534b1db25970b01b8d1968830970c-pi
- pure python: https://community.alteryx.com/t5/Data-Science-Blog/RPy2-Combining-the-Power-of-R-Python-for-Data-Science/ba-p/138432
The ultimate preference is doing a pure python interface (probably with a similar generic bridge, as we are doing for bioLQM/GINsim) ; but for now we can already use the %%R magic.

**Comment by pauleve** [comment]
I've made a short tutorial showing the two methods:
https://github.com/colomoto/colomoto-docker/blob/next-R/tutorials/R-BoolNet/Random%20BN%20generation%2C%20loading%20with%20biolqm%20or%20minibn.ipynb

It might be more user friendly to create a two lines python package to load the R package, and also having a menu in the Jupyter interface. I'm also wondering where to put this module - within colomoto-jupyter ?

**Comment by pauleve** [comment]
merged and tagged
