### ISSUE TITLE
Adding libsbml

### ISSUE THREAD

**Issue by lunaticstarr** [colomoto/colomoto-docker#156]
I am currently working on logical models, specifically, we have developed a model merging workflow that relies on SBML-qual for integrating and analyzing logical models. We have used the CoLoMoTo Docker image extensively and found it really helpful. However, we noticed that libSBML, which is essential for working with SBML-qual models, is not included in the image. While your guideline for integrating tools locally is helpful, it would be great to have libSBML pre-installed because of the increasing adoption of SBML-qual as a standard format. Would it be something possible in the future release?
Thank you for your efforts in supporting the modeling community and for considering this request.

**Comment by pauleve** [comment]
Hello,  and thanks for your comment.
Which package are you referring to, specifically? python-libsbml is already shipped within the Docker. Do you have another one in mind?

**Comment by lunaticstarr** [comment]
> Hello, and thanks for your comment. Which package are you referring to, specifically? python-libsbml is already shipped within the Docker. Do you have another one in mind?

Thanks for the reply. Yes I am talking about python-libsbml package. I am using `colomoto/colomoto-docker:2024-03-01`,and it seems unavailable. 
![Screenshot 2024-12-29 at 12 36 22](https://github.com/user-attachments/assets/e5de78f6-65ea-45ac-8530-d2e8981bdfc3)

**Comment by pauleve** [comment]
You can try with the latest available `2024-11-01`
