### ISSUE TITLE
NuSMVARCTL should be 32bit

### ISSUE THREAD

**Issue by pauleve** [colomoto/colomoto-docker#2]
Ensure that NuSMVARCTL works properly.

**Comment by ptgm** [comment]
Running NuSMVARCTL compiled at 64bits leads to this:
*** stack smashing detected ***: NuSMVARCTL terminated                                                                            
Aborted (core dumped)

**Comment by pauleve** [comment]
Do you have a 32bit binary available for download somewhere? Otherwise, we can store it in the github.

**Comment by ptgm** [comment]
Yes, consider this binary http://pedromonteiro.org/software/NuSMV-32bit-2.2.2-ARCTL
It's compiled at 32bits, can run on a 64bit machine with multilib support.

**Comment by pauleve** [comment]
Could you make a static executable? (as it is done with NuSMV) 
It seems there is an --enable-static option for configure ; otherwise setting LDFLAGS=-static may work...

**Comment by ptgm** [comment]
Sure, it's here http://pedromonteiro.org/software/NuSMV-32bit-2.2.2-ARCTL-static

**Comment by pauleve** [comment]
Awesome! Thx.
