### ISSUE TITLE
Use a new random container name at each SnakeMake workflow execution

### ISSUE THREAD

**Issue by chernan** [colomoto/colomoto-docker#20]
In order to simplify the Docker container handling during the SnakeMake workflow execution, use a new container name each time 'docker run -d' is invoked, similarly to what is done for the output folder.
This will allow to simplify the onstart, onerror, onsuccess calls.

**Comment by chernan** [comment]
A new tag and consequently a new container is now created at each run of the SnakeMake. onstart, onerror, onsuccess methods were removed, but can be added back if we want.

**Comment by pauleve** [comment]
Great!
Probably you should add `--rm` to the `docker run` command and add a simple rule to kill the container on success or error (could be simply that if the output file "CoLoMoTo_image_available" exists, perform a docker stop)

**Comment by pauleve** [comment]
Could also be doing a docker stop in the rule "all", as if there is an error, it may be useful to still have access to the container.

**Comment by chernan** [comment]
I added the --rm option, as well as the docker stop in rule all. Looks very clean like that, good idea.
