### ISSUE TITLE
Version number specification for reproducible builds

### ISSUE THREAD

**Issue by aurelien-naldi** [colomoto/colomoto-docker#22]
We want to specify the version of the included tools to ensure reproducible builds

A few points to discuss:
* how specific should we be. For example, should we track the exact version of openjdk or trust that the latest 8.0 package is acceptable? In this case, I would rather pick 8.0 than 8.0.121
* I will add version numbers to the conda metapackage, should we duplicate them in docker as well?
* How many indirect dependencies should be listed in the main metapackage? I see a good reason for fixing the clingo version there as it is used by several tools, but what about others?
* its currently uses a rolling release, should we pick a snapshot?

**Comment by pauleve** [comment]
One way to think about it is the process for adding and upgrading a package.
To ensure a manageable collection of software, it is indeed a good idea to impose a packaging method, and conda is a good choice.
This tells that if someone wants its software integrated, it has to provide a conda package and maintain it, which is perfectly arguable.

Here is a proposition of process:
* the maintainer of the software/library provides a conda package and maintain it
* for adding/upgrading a package, it creates a pull request on colomoto-docker with a line of the form:
```
RUN conda -y -c mychannel [...] mypackage=myversion && conda clean -y --all
```
* one of the maintainer of the docker accepts the change, which triggers an automatic rebuild
* then, a tag can be created so the image can be referred to with a specific version (for instance with a timestamp), which is necessary to ensure reproducibility (we'll have to determine a policy for that)

The advantages are the following:
- no need to maintain a metapackage. It may still be useful though for usage outside of docker, but then the metapackage does not need to care about the version of its dependencies, so it will be modified only when adding/removing packages
- the burden of upgrading a package in the docker is low becasue most of the job is done by the maintainer of the tool (i.e., publishing updated conda package)
- one can propose an ordering of the RUN commands, putting first the software which receives little uprades and then the one updated regularly to take advantage of the docker layers.
- contributors only need to know and interact with colomoto-docker repository

Regarding the questions on dependencies, I think the metapackage should not mention indirect dependencies. It is at the level of the software to indicate properly the constraints on the versions.

Any alternative process for adding/upgrading a tool?

Related question: is it possible to have automatic building/pushing of conda packages? Or can we allow several users to upload to the colomoto channel?
