### ISSUE TITLE
Fix SnakeMake case study

### ISSUE THREAD

**Issue by pauleve** [colomoto/colomoto-docker#26]
The current SnakeMake case study is wrong, especially the file 
https://github.com/colomoto/colomoto-docker/blob/master/usecases/snakemake/Models/2016_CellCycle_Traynard/Traynard_MultiLevel_MamCC_Apr2016_property.smv
which cannot be append as is to the NuSMV model.

Lines 
```
INIT xxxx ; SPEC yyy
```
should be replaced with
```
SPEC xxxx -> yyyy
```

**Comment by chernan** [comment]
@aurelien-naldi did you know about this ? All the properties files I've seen so far, made by either Wassim or Pauline, used the INIT xxxx ; SPEC yyy format.

**Comment by chernan** [comment]
Properties file was modified according to suggestion. Please double check, in case I forgot something.
