### ISSUE TITLE
Win 7, error (subprocess File not found)

### ISSUE THREAD

**Issue by xhajnal** [colomoto/colomoto-docker#33]
![image](https://user-images.githubusercontent.com/23458520/41849362-f0d531f2-7880-11e8-93e1-12d498d113b3.png)

the last sentence is "No such file or directory"

**Comment by pauleve** [comment]
Is it fixed? As you are on Win7, I guess you have to use Docker Toolbox, and the colomoto-docker command should be ran in the "Docker Terminal"

**Comment by xhajnal** [comment]
Works perfectly now (with the Docker Toolbox), I must have missed the first sentence in readme.
