### ISSUE TITLE
the X (next) operator does not work in temporal logic

### ISSUE THREAD

**Issue by xhajnal** [colomoto/colomoto-docker#35]
```
from colomoto.temporal_logics import *
prop = {"prop": AU(True,True)} 
prop = {"prop": EU(True,True)} 

prop = {"prop": AF(True)} 
prop = {"prop": EF(True)} 

prop = {"prop": AG(True)} 
prop = {"prop": EG(True)} 

prop = {"prop": F(True)}
prop = {"prop": G(True)}
prop = {"prop": X(True)}

prop = {"prop": AX(True)} 
prop = {"prop": EX(True)}
```

Results in an error `NameError: name 'X' is not defined`´
same for **AX** and **EX**

(using 2018-08-17)

**Comment by pauleve** [comment]
Thanks for the report.
It is fixed by https://github.com/colomoto/colomoto-jupyter/commit/2f45410c6fc8d2b1e6ba5742305f908c9b8c669e
which will be included in the next release of colomoto_jupyter, then in the next docker image.
