### ISSUE TITLE
Use case: Stable states and model checking

### ISSUE THREAD

**Issue by chernan** [colomoto/colomoto-docker#4]
A first use case to implement would be :
- From a GINsim model, compute its sable states,
- Export in NuSMV format,
- Check a set of properties using NuSMV.

**Comment by chernan** [comment]
Started a first implementation using SnakeMake.

**Comment by chernan** [comment]
Workflow done, to be tested. Comments are welcome.

**Comment by chernan** [comment]
Commit of a draft Jupyter notebook corresponding to the use case.

**Comment by pauleve** [comment]
The current workflow is wrong for the model-checking part: it is not possible to check properties for different INIT in a single file : NuSMV makes the conjonction of all init statements, which in this case lead to unsatisfiable constraint, therefore, no initial state are considered, and all the properties become true (you can easily check that a property like SPEC (CycD=1 & CycD=0) is true in your smv file.

Given the properties, the way to fix this is to ask GINsim to not export the initial state (no INIT statement), and use implications on the initial state for the properties.
(SPEC condition_on_init -> property)
I'll start implement this next week using the new NuSMV/Colomoto python API.

@aurelien-naldi is it possible to ask ginsim to skip the INIT generation using the NuSMVConfig object?

**Comment by pauleve** [comment]
I've started in the dev branch a new version of this notebook:
https://nbviewer.jupyter.org/github/colomoto/colomoto-docker/blob/dev/usecases/Usecase%20-%20Logical%20model%20of%20the%20mammalian%20cell%20cycle.ipynb

Main question (@chernan @aurelien-naldi ): any idea how the Cycle1 variable has been generated?

**Comment by chernan** [comment]
The SnakeMake was updated according to recent developments and suggestions. But I noticed that some of the properties are now evaluated as wrong even if they are exactly the same as in the original smv file.
Need to double check with @aurelien-naldi if the NuSMV export is done properly.

**Comment by pauleve** [comment]
Maybe try by putting parentheses before the `->`, I'm not sure of the priorities:
```
SPEC (condition1 & condition2 & ...) -> ...
```

**Comment by chernan** [comment]
Same result.

**Comment by pauleve** [comment]
With the original smv file on http://ginsim.org/node/189
if I uncomment the first property, NuSMV says false which is consistent with the results using the SnakeMake worflow.
Therefore, I guess it is expected that some properties are false and others are true.
I close the bug related to SnakeMake workflow ; I suggest to close that one too.
