### ISSUE TITLE
Update snakemake use case with docker run/exec

### ISSUE THREAD

**Issue by pauleve** [colomoto/colomoto-docker#6]
The snakemake command file should first start a container for `colomoto/colomoto-docker` (`docker run`) and use it for executing commands (`docker exec`).
The docker run call should probably override the default CMD (which starts the jupyter server).

**Comment by chernan** [comment]
Done on 07/09/2017 (commit a74cc9e1b0fe3c9d3656c0b4f065e3d27a46687c).

'docker create' creates a new container from the colomoto-docker image with the necessary folder mapping, and 'docker start' starts it. Further 'docker run' calls have been replaced by 'docker exec' calls in order to re-use this container instead of creating a new one each time.
At the beginning and at the end of the workflow execution, the script checks whether the container already exists and stop/delete it if necessary.

If no further comment, I'll close the issue next Tuesday.

**Comment by pauleve** [comment]
I put comments on your commit.

PS: you can use "issue #6" in the commit message to directly link to this page.

**Comment by chernan** [comment]
Ok, thanks. Did the change in the snakefile.

**Comment by pauleve** [comment]
Thanks! Looks good to me.
What about my other comment on having a simpler way to shutdown/restart the docker?
something like
```
docker stop {COLOMOTOCONT} 2>/dev/null && docker rm {COLOMOTOCONT} || true
```
in on{error,success,start} should be equivalent to the long python function ; and is much simpler to explain and copy-paste.

Also, to be able to run different instances in parallel without having to change manually COLOMOTOCONT, you could use a dynamic container id, for instance the one returned by docker run -d (without --name) (and remove the onstart target).
But I don't know if it is easy to do such a thing with snakemake. Ideally you would print the container id in a file (`docker run -d .... > {output}`), and use its content for docker exec and docker stop/rm ; or export its content as a global variable (COLOMOTOCONT).
An alternative is to add a random string to COLOMOTOCONT.

**Comment by chernan** [comment]
Sorry, I missed the other comment...
I'm personally not in favour of redirecting all errors to /dev/null. If there is an important error, it will just go unnoticed, and that's not good for the reliability of the workflow (and of workflows in general). I prefer treating each case that we want to cover separately, even if it means having a longer python function. And I don't think that it's so much more complicated to explain with the code documentation I already wrote.
About the second point, I thought about it, indeed. The random string is my preferred solution. Just as I already create a separate output folder for each run using the timestamp, it would be easy to use this tag to create a new name for the container at each docker run -d invocation. This solution would be much easier to set up than recovering the dynamic ID in a file, etc. But considering that this was not included in the issue for milestone 1, I left it as-is.
If we consider that it's a point worth adding to milestone 1, I can create an issue and implement the random string to the container name.

**Comment by pauleve** [comment]
Having this random container name would be nice for M1!
And it would solve the on{start,success,error}, as onstart will become empty, onsuccess will be docker stop & rm, and onerror could do the stop & rm as well, without any 2>/dev/null.
It will allow us to show a generic and simple template for snakemake

**Comment by chernan** [comment]
Hi Loïc, I hope BC2 was nice. Thanks for your comment! 
I'll try to do it sometime next week. In the meantime, I close this issue and create a new one about the unique container ID.
