### ISSUE TITLE
Docker images on GitHub Packages

### ISSUE THREAD

**Issue by pauleve** [colomoto/colomoto-docker#75]
Given the coming DockerHub retention policy, we should improve the archiving of our images.
Besides ensuring that old images can still be built (issue #76), we can opt for mirrors for hosting the Docker images. And GitHub seems perfectly suited for that:
https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages

TODO
- [x] workflows: push images both to docker.hub and github packages
- [x] copy all released images so far on github packages
- [x] `colomoto-docker`: support multiple registries, with fallback when no image is found.

**Comment by aurelien-naldi** [comment]
GitHub seems to plan moving github packages to a more generic system currently in beta. When this is in place, it will be limited to 2GB of storage per organisation, it won't be enough to maintain old images.

https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images

https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-packages

**Comment by pauleve** [comment]
I'm not sure how to read their sentences actually. To me, "GitHub Packages usage is free for public packages" means that public repositories have unlimited storage resources, and that the given limits are for private repositories.
We'll see..

Anyway:
- I already moved (in principle) the storage of (future) image to their new repository
- docker postponed the application of the retention policy to "a later date", but in any case, we should rely on them.
- storing them on zenodo is definitely a must do feature (I'm also thinking at "resurecting" images when it is no longer on dockerhub and someone is trying to access it)

**Comment by aurelien-naldi** [comment]
You are right, it sounds like public images will not be restricted. If we already have image pushed to both the docker and github repository, it's already a big improvement! As zenodo is discussed in #78, all which remains is making sure that old images are preserved by making sure that there are downloaded at least once every few months.

**Comment by pauleve** [comment]
That is indeed a strategy (pulling from docker.hub images regularly); the other one I had in mind was to use github as primary registry, or as fallback registry whenever the image is not found on dockerhub (with a further fallback on zenodo).
that is not mutually exclusive (and there is no rush at the moment)
I liked the idea of not pulling automatically docker.hub to have an idea of most used images, and at some point, they will maybe include storage restrictions as well..

**Comment by pauleve** [comment]
For now I added github as fallback and keep docker.hub as primary mirror; maybe in the future we'll better switch the ordering of mirrors, the time that the Docker feature stabilizes on github
