### ISSUE TITLE
New tool: booleannet

### ISSUE THREAD

**Issue by aurelien-naldi** [colomoto/colomoto-docker#79]
The format is already supported by bioLQM (with some fixes in the pipeline).
Booleannet is a python package available at https://github.com/ialbert/booleannet

The last release supports only python2 but Python3 support is in git master.

* [X] conda recipe in colomoto-conda
* [x] example notebook
* [x] Added to the Dockerfile

**Comment by aurelien-naldi** [comment]
I asked Istvan and Reka Albert if they agree for the addition and want to provide a tutorial.
Unless they ask us to not include it, I plan to add it to the next release (they have a couple of examples which can serve as basis for the tutorial).

BioLQM and GINsim will gain a "to_booleannet" function (and to_pyboolnet, which was missing). Do we need other integration points?

**Comment by pauleve** [comment]
I will add these conversion to minibn as well.

**Comment by aurelien-naldi** [comment]
Istvan and Reka agreed, so I added the conversion to GINsim-python. I will add the tutorial and the entry in the Docker file next week.

**Comment by pauleve** [comment]
Actually, I forgot that the input format was not in bnet, so it makes little sense for a `minibn.to_booleannet` as it will have to go through biolqm.
In the future, we may add automatic shortcuts like that though, but I prefer we keep it explicit for now.

**Comment by aurelien-naldi** [comment]
Added by 32c868aa45669b0f9bc35fd87233e3418666c5f5, and the current "next" image
