### ISSUE TITLE
Document Python packages

### ISSUE THREAD

**Issue by jonrkarr** [colomoto/colomoto-docker#96]
This is a great resource. Documentation for the all of Python packages for each of the simulation tools would make this much easier to use.

**Comment by pauleve** [comment]
Yes, we need to push our efforts on the documentation...
Actually, many Python modules are already documented. We should probably link the documentation in the description of the tools at https://colomoto.github.io/colomoto-docker/
Then, for tools without documentation, we could at least generate a basic one with readthedocs, even without complete docstrings. I'm hoping to find the time for working on the documentation during the summer.

**Comment by pauleve** [comment]
The new website now adds a link to each individual Python package + at least one tutorial.
Further documentation for each package is on the responsibility of their maintainers.
